version: '3.3'
services:
  mongo:
    image: mongo:4.0-xenial
    container_name: loopmongo_container
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
  server:
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/Task